# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # Krok 2: Usuń stare pliki graficzne, jeśli istnieją
      - name: Remove old plots (if they exist)
        run: |
          rm -f scatter_plots.png histogram.png distribution.png correlation_heatmap.png

      # Krok 3: Pobierz .csv'ke
      - name: Download .csv file
        run: |
          curl -o CollegeDistance.csv https://vincentarelbundock.github.io/Rdatasets/csv/AER/CollegeDistance.csv

      # Krok 4: Zainstaluj Python i zależności
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Krok 5: Instalowanie Dependencji
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Krok 6: Uruchom analizę i wygeneruj wykresy
      - name: Run analysis and generate plots
        run: python eda.py

      # Krok 7: Inżynieria cech i przygotowanie danych
      - name: Feature Engineering and Data Preparation
        run: python feature_engineering.py

      # Krok 8: Proba PyCaret
      - name: AutoML with PyCaret
        run: python model_training.py

      # Krok 9: Zaktualizuj README.md
      - name: Update README.md
        run: |
          chmod +x update_readme.sh
          bash update_readme.sh

      # Krok 10: Push README.md
      - name: Commit and push updates to README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md histogram.png histogram_processed.png scatter_plots.png scatter_plots_processed.png distribution.png distribution_processed.png correlation_heatmap.png --force
          git commit -m "Auto update README.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      # DEBUG - ARTEFAKTY
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: |
            feature_importance.png