#!/bin/bash

{
  echo "### Ostatnia aktualizacja: $(date)"
  echo "# Jak pobrać projekt?"

  echo "## Uruchomienie lokalne"
  echo "1. Sklonuj repozytorium przy użyciu poniższej komendy:"
  echo "\`\`\`bash"
  echo "git clone https://github.com/PJATK-ASI-2024/s24353_Bank-Marketing.git"
  echo "\`\`\`"
  echo "2. Przełącz się na odpowiedni branch"
  echo "\`\`\`bash"
  echo "cd s24353_Bank-Marketing"
  echo "git checkout Projekt-7-Publikacja-Modelu"
  echo "\`\`\`"
  echo "3. Otwórz projekt w swoim preferowanym IDE (Integrated Development Environment) takim jak PyCharm czy VS Code."
  echo "4. Zainstaluj potrzebne dependencje:"
  echo "\`\`\`bash"
  echo "pip install -r requirements.txt"
  echo "\`\`\`"
  echo "5. Wygeneruj model przy użyciu Airflow'a. [Patrz sekcja poniżej.](#budowa-modelu-przy-użyciu-apache-airflow)"
  echo "6. Odpal serwis REST API poprzez wywołanie \`app_local.py\`. Aplikacja powinna słuchać na porcie 5000."
  echo "7. Wyślij przykładowe zapytanie do aplikacji z użyciem cURL'a na endpoint \`/predict\`."
  echo "8. Przykłady zapytań:"
  echo ""
  echo "\`JSON\`"
  echo "\`\`\`bash"
  echo "curl -X POST http://localhost:5000/predict -H \"Content-Type: application/json\" -d '["
  echo "    {"
  echo "        \"age\": 34,"
  echo "        \"job\": \"admin.\","
  echo "        \"marital\": \"married\","
  echo "        \"education\": \"university.degree\","
  echo "        \"default\": \"no\","
  echo "        \"housing\": \"yes\","
  echo "        \"loan\": \"no\","
  echo "        \"contact\": \"cellular\","
  echo "        \"month\": \"jul\","
  echo "        \"day_of_week\": \"thu\","
  echo "        \"duration\": 417,"
  echo "        \"campaign\": 1,"
  echo "        \"pdays\": 6,"
  echo "        \"previous\": 3,"
  echo "        \"poutcome\": \"success\","
  echo "        \"emp.var.rate\": -1.7,"
  echo "        \"cons.price.idx\": 94.215,"
  echo "        \"cons.conf.idx\": -40.3,"
  echo "        \"euribor3m\": 0.899,"
  echo "        \"nr.employed\": 4991.6"
  echo "    }"
  echo "]'"
  echo "\`\`\`"
  echo "9. Alternatywnie, możesz użyć \`test_response.py\` które zawiera gotowe przykłady zapytań."

  echo "## Budowa modelu przy użyciu Apache Airflow"
  echo "1. Przejdź do folderu z plikami Airflow'a:"
  echo "\`\`\`bash"
  echo "cd airflow"
  echo "\`\`\`"
  echo "2. Zbuduj customowy obraz airflow z potrzebnymi dependencjami:"
  echo "\`\`\`bash"
  echo "docker build ."
  echo "\`\`\`"
  echo "3. Uruchom airflow z użyciem docker-compose:"
  echo "\`\`\`bash"
  echo "docker-compose up -d"
  echo "\`\`\`"
  echo "4. Otwórz przeglądarkę i przejdź do [http://localhost:8080](http://localhost:8080)."
  echo "5. Zaloguj się domyślnymi danymi: login: \`airflow\`, hasło: \`airflow\`."
  echo "5. Przejdź przez wszystkie DAG'i po kolei: \`download-public-split-save\` -> \`download_cloud_clean_standard-normalize_save\` -> \`building_model\`."
  echo "6. Oczekuj na zakończenie procesu budowy modelu."
  echo "7. Po zakończeniu procesu, model zostanie zapisany w folderze \`models\`."

  echo "## Uruchomienie przy użyciu Docker'a"
  echo "1. Pobierz obraz z DockerHub'a:"
  echo "\`\`\`bash"
  echo "docker pull serafinski/model-api"
  echo "\`\`\`"
  echo "2. Uruchom kontener z pobranym obrazem (wymaga otwarcia portu 5000 - jeżeli zajęty można zmienić go na dowolny inny: \`[twoj_port]:5000\`):"
  echo "\`\`\`bash"
  echo "docker run -p 5000:5000 serafinski/model-api:latest"
  echo "\`\`\`"
  echo "3. Wyślij przykładowe zapytanie do aplikacji z użyciem cURL'a na endpoint \`/predict\`."
  echo "4. Przykłady zapytań:"
  echo ""
  echo "\`JSON\`"
  echo "\`\`\`bash"
  echo "curl -X POST http://localhost:5000/predict -H \"Content-Type: application/json\" -d '["
  echo "    {"
  echo "        \"age\": 34,"
  echo "        \"job\": \"admin.\","
  echo "        \"marital\": \"married\","
  echo "        \"education\": \"university.degree\","
  echo "        \"default\": \"no\","
  echo "        \"housing\": \"yes\","
  echo "        \"loan\": \"no\","
  echo "        \"contact\": \"cellular\","
  echo "        \"month\": \"jul\","
  echo "        \"day_of_week\": \"thu\","
  echo "        \"duration\": 417,"
  echo "        \"campaign\": 1,"
  echo "        \"pdays\": 6,"
  echo "        \"previous\": 3,"
  echo "        \"poutcome\": \"success\","
  echo "        \"emp.var.rate\": -1.7,"
  echo "        \"cons.price.idx\": 94.215,"
  echo "        \"cons.conf.idx\": -40.3,"
  echo "        \"euribor3m\": 0.899,"
  echo "        \"nr.employed\": 4991.6"
  echo "    }"
  echo "]'"
  echo "\`\`\`"

  echo "## Zapytanie do modelu na platformie GCP"
  echo "1. Wyślij przykładowe zapytanie do modelu na platformie GCP na endpoint \`https://s24353-683779376482.europe-central2.run.app/predict\`."
  echo "2. Przykłady zapytań:"
  echo ""
  echo "\`JSON\`"
  echo "\`\`\`bash"
  echo "curl -X POST https://s24353-683779376482.europe-central2.run.app/predict -H \"Content-Type: application/json\" -d '["
  echo "    {"
  echo "        \"age\": 34,"
  echo "        \"job\": \"admin.\","
  echo "        \"marital\": \"married\","
  echo "        \"education\": \"university.degree\","
  echo "        \"default\": \"no\","
  echo "        \"housing\": \"yes\","
  echo "        \"loan\": \"no\","
  echo "        \"contact\": \"cellular\","
  echo "        \"month\": \"jul\","
  echo "        \"day_of_week\": \"thu\","
  echo "        \"duration\": 417,"
  echo "        \"campaign\": 1,"
  echo "        \"pdays\": 6,"
  echo "        \"previous\": 3,"
  echo "        \"poutcome\": \"success\","
  echo "        \"emp.var.rate\": -1.7,"
  echo "        \"cons.price.idx\": 94.215,"
  echo "        \"cons.conf.idx\": -40.3,"
  echo "        \"euribor3m\": 0.899,"
  echo "        \"nr.employed\": 4991.6"
  echo "    }"
  echo "]'"
  echo "\`\`\`"

  echo "## Wysyłanie zapytań przy użyciu Postmana"
  echo "1. Pobierz i zainstaluj [Postmana](https://www.postman.com/downloads/)."
  echo "2. Otwórz Postmana i zaimportuj plik [ASI.postman_collection.json](ASI.postman_collection.json)."
  echo "3. Wybierz odpowiedni request i wyślij go do aplikacji."

  echo "# Przewidywanie skuteczności kampanii marketingowej banku"

  echo "## Plan projektu"

  echo "### Opis tematu i problemu biznesowego/technicznego"
  echo "Projekt dotyczy przewidywania skuteczności kampanii telemarketingowych prowadzonych przez bank, których celem jest nakłonienie klientów do wykupienia lokat terminowych."
  echo ""
  echo "W bankowości skuteczność kampanii marketingowych ma kluczowe znaczenie dla zwiększenia zysków i zminimalizowania kosztów związanych z kontaktowaniem się z niechętnymi klientami."
  echo ""
  echo "Dlatego zrozumienie, które cechy klientów oraz wskaźniki społeczno-ekonomiczne zwiększają szansę na sprzedaż lokaty, pozwala bankom optymalizować działania marketingowe, skutecznie zarządzać zasobami i w efekcie osiągać lepsze wyniki finansowe."

  echo "### Źródło danych, ich charakterystyka i uzasadnienie wyboru zbioru danych"
  echo "Dane pochodzą z publicznie dostępnego zestawu Bank Marketing opublikowanego w 2014 roku przez Sérgio Moro, Paulo Cortez i Paulo Ritę dostępnego na [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/222/bank+marketing)."
  echo ""
  echo "Dane zawierają informacje z okresu od maja 2008 do listopada 2010 roku o klientach banku.
  Zostały one wzbogacone o pięć wskaźników społeczno-ekonomicznych na poziomie narodowym (m.in. kwartalna stopa zatrudnienia, miesięczny wskaźnik cen konsumpcyjnych, euribor), publikowanych przez Banco de Portugal.
  Zbiór zawiera 41 188 rekordów oraz 21 atrybutów dotyczących klientów banku, atrybutów kampanii telemarketingowej oraz danych makroekonomicznych, dzięki czemu analitycy mogą zrozumieć wpływ zarówno danych demograficznych, jak i kontekstu ekonomicznego na decyzje klientów."
  echo ""
  echo "Zbiór ten jest idealny do zastosowań związanych z modelowaniem predykcyjnym, gdyż zawiera wiele zróżnicowanych zmiennych wpływających na wyniki kampanii."

  echo "### Cele projektu"
  echo "Głównym celem projektu jest stworzenie modelu predykcyjnego, który prognozuje, czy dany klient zdecyduje się na zakup lokaty terminowej."

  echo "### Diagram przepływu"
  echo "![Diagram przepływu](workflow_diagram.png)"

  ##############################
  echo "## Analiza danych"

  echo "### Opis zmiennych"
  echo "Zmienne klienta:"
  echo "1. __age__ — wiek klienta (zmienna liczbowa)"
  echo "2. __default__ — czy klient ma niespłacony kredyt (zmienna kategoryczna)"
  echo "3. __education__ — wykształcenie klienta (zmienna kategoryczna)"
  echo "4. __housing__ — czy klient posiada kredyt mieszkaniowy (zmienna kategoryczna)"
  echo "5. __job__ — rodzaj pracy klienta (zmienna kategoryczna)"
  echo "6. __loan__ — czy klient ma pożyczkę (zmienna kategoryczna)"
  echo "7. __marital__ — stan cywilny klienta (zmienna kategoryczna)"
  echo ""

  echo "Zmienne związane z ostatnim kontaktem z klientem w bieżącej kampanii:"
  echo "1. __contact__ — typ komunikacji z klientem (zmienna kategoryczna)"
  echo "2. __day_of_week__ — dzień tygodnia ostatniego kontaktu (zmienna kategoryczna)"
  echo "3. __duration__ — czas trwania ostatniego kontaktu, w sekundach (zmienna liczbowa)"
  echo "4. __month__ — miesiąc ostatniego kontaktu w roku (zmienna kategoryczna)"
  echo ""

  echo "Inne zmienne:"
  echo "1. __campaign__ — liczba kontaktów wykonana podczas aktualnej kampanii dla danego klienta (zmienna liczbowa, wlicza ostatni kontakt)"
  echo "2. __pdays__ — liczba dni od ostatniego kontaktu z klientem podczas poprzedniej kampanii (zmienna liczbowa, 999 - nie było wcześniejszego kontaktu z klientem)"
  echo "3. __poutcome__ — wynik poprzedniej kampanii marketingowej (zmienna kategoryczna)"
  echo "4. __previous__ — liczba kontaktów wykonana przed aktualną kampanią dla danego klienta (zmienna liczbowa)"
  echo ""

  echo "Zmienne związane z kontekstem społecznym i ekonomicznym:"
  echo "1. __cons.conf.idx__ — indykator miesięczny, wskaźnik ufności konsumenckiej (zmienna liczbowa)"
  echo "2. __cons.price.idx__ — indykator miesięczny, wskaźnik cen towarów i usług konsumpcyjnych (zmienna liczbowa)"
  echo "3. __emp.var.rate__ — indykator kwartalny, wskaźnik zmienności zatrudnienia (zmienna liczbowa)"
  echo "4. __euribor3m__ — indykator dzienny, 3-miesięczna stopa EURIBOR — referencyjna wysokość oprocentowania depozytów i kredytów na rynku międzybankowym strefy euro (zmienna liczbowa)"
  echo "5. __nr.employed__ — indykator kwartalny, liczba pracowników (zmienna liczbowa)"

  echo "Zmienna wynikowa:"
  echo "__y__ — czy klient założył lokatę (zmienna binarna: 'yes' lub 'no')"

  echo "### Rozkład zmiennych numerycznych"
  cat numeric_analysis.txt

  echo "### Rozkład zmiennych kategorycznych"
  cat categorical_analysis.txt

  echo "### Wizualizacje"
  echo "Histogramy"
  echo "![Histogramy](histograms.png)"

  echo "Wykresy pudełkowe"
  echo "![Wykresy pudełkowe](boxplots.png)"

  echo "Macierz korelacji"
  echo "![Macierz korelacji](correlation_matrix.png)"

  echo "### Wnioski na podstawie automatycznej analizy danych - Pandas Profiling"

  echo "1. Przegląd zbioru danych:"
  echo "* Zbiór danych zawiera 28,831 obserwacji i 21 zmiennych."
  echo "* Brak brakujących wartości – dane są kompletne."
  echo "* Występuje 7 duplikatów wierszy, co stanowi mniej niż 0,1% danych, więc ma minimalny wpływ na analizy."

  echo "2. Typy zmiennych:"
  echo "* Zbiór danych zawiera 10 zmiennych numerycznych, 10 kategorycznych oraz 1 logiczną."
  echo "* Różnorodność ta sugeruje możliwość zastosowania różnorodnych analiz, zwłaszcza przy kodowaniu zmiennych kategorycznych."

  echo "3. Wnioski z korelacji:"
  echo "* Kilka zmiennych wykazuje wysoką korelację, co może wskazywać na potencjalną współliniowość. W szczególności:"
  echo "    * \`cons.conf.idx\` i \`month\`"
  echo "    * \`emp.var.rate\` z \`cons.price.idx\` i \`euribor3m\`"
  echo "    * \`pdays\` z \`poutcome\` i \`previous\`"
  echo "* Korelacje te sugerują, że niektóre zmienne mogą dostarczać podobnej informacji, co można zoptymalizować w modelach poprzez redukcję nadmiarowości."

  echo "4. Niezrównoważone zmienne:"
  echo "* W przypadku kilku zmiennych występuje wysoki poziom niezrównoważenia, co może wpływać na jakość modeli predykcyjnych:"
  echo "    * \`default \` (skos 53%)"
  echo "    * \`loan\` (skos 51,2%)"
  echo "    * \`poutcome\` (skos 56,5%)"
  echo "* Radzenie sobie z tymi niezrównoważeniami może wymagać zastosowania technik takich jak próbkowanie lub nadawanie wag w klasyfikacji."

  echo "5. Statystyki opisowe:"
  echo "* Wiele zmiennych wykazuje wysokie wartości skośności i kurtozy, co sugeruje nienormalny rozkład. Na przykład:"
  echo "    * Odchylenie standardowe niektórych zmiennych, takich jak \`cons.price.idx\` i \`emp.var.rate\`, jest znacznie zróżnicowane, co może wymagać normalizacji lub skalowania w procesie przetwarzania wstępnego."
  echo "* Zmienna \`pdays\` zawiera znaczny procent zerowych wartości (86,2%), co może wymagać przekształcenia dla lepszej interpretowalności i efektywności modelu"

  echo "## Jak czyszczono dane"

  echo "1. Usuwanie wierszy z nieznanymi wartościami w kluczowych kolumnach:"
  echo "* Kolumna \`job\`: Usunięto 244 wiersze, w których wartość w tej kolumnie wynosiła \`unknown\`."
  echo "* Kolumna \`marital:\` Usunięto 42 wiersze, w których wartość wynosiła \`unknown\`."
  echo "* Kolumna \`education\`: Usunięto 1110 wierszy z wartością \`unknown\`."
  echo "* Kolumna \`housing\`: Usunięto 657 wierszy z wartością \`unknown\`."
  echo "* Kolumna \`loan\`: Po usunięciu poprzednich wierszy w tej kolumnie nie wystąpiły przypadki wartości \`unknown\`, więc nie usunięto żadnych wierszy."

  echo "2. Usuwanie wierszy ze znikomymi wartościami:"
  echo "* Kolumna \`default\`: Usunięto 3 wiersze, gdzie wartość wynosiła \`yes\`. Wartości było tak mało, że nie miały wpływu na analizę."

  echo "3. Usunięcie zmiennej \`duration\`:"
  echo "* Zmienna \`duration\` reprezentuje czas trwania ostatniego kontaktu z klientem w bieżącej kampanii. Analiza wykazała, że zmienna ta miała bardzo duży wpływ na prognozy modelu — często dwukrotnie większy niż wpływ kolejnych cech. Przykładem jest przypadek, gdy wartość \`duration=0\`, co prawie zawsze skutkuje prognozą \`y=no\`."
  echo "* Zmienna \`duration\` nie jest znana przed rozpoczęciem kontaktu z klientem. Ponadto, po zakończeniu rozmowy, informacja o decyzji klienta (czy wziął lokatę) jest już dostępna. W związku z tym użycie tej zmiennej mogłoby prowadzić do nienaturalnych prognoz, niewykorzystujących rzeczywistych informacji dostępnych przed kontaktem."
  echo "Zdecydowano się na usunięcie zmiennej \`duration\` z zestawu danych, ponieważ wprowadzała nierealistyczny aspekt predykcji i nie wspierała poprawy rzeczywistej jakości modelu."

  echo "## Wybór modelu przy użyciu AutoML - PyCaret"
  echo "PyCaret podzieli dane na w stosunku 70/30 gdzie 70% to dane treningowe: \`train_size=0.7\`"
  echo "### Metryki modeli"
  echo "Najlepszy model został wybrany wg. poniższych metryk oceny modelu:"
  echo "* MAE (Mean Absolute Error): Średnia wartość bezwzględnych różnic między rzeczywistymi a przewidywanymi wartościami. Im niższa wartość, tym lepsze dopasowanie modelu. Mniejsza wartość MAE oznacza lepszy model."
  echo "* MSE (Mean Squared Error): Średnia kwadratów różnic między rzeczywistymi a przewidywanymi wartościami. Większa waga jest nadawana większym błędom. Mniejsza wartość MSE jest lepsza, ponieważ oznacza mniej odchyleń."
  echo "* RMSE (Root Mean Squared Error): Pierwiastek kwadratowy z MSE. Daje wynik w tej samej skali co dane. Mniejsza wartość RMSE oznacza lepsze dopasowanie modelu."
  echo "* R^2 (R-Squared): Proporcja wariancji w zależnej zmiennej wyjaśnionej przez model. Im wyższa wartość R^2, tym lepsze dopasowanie modelu. R^2 bliskie 1 oznacza bardzo dobre dopasowanie."
  echo "* RMSLE (Root Mean Squared Log Error): Pierwiastek kwadratowy z błędu logarytmicznego. Mniejsza wartość RMSLE jest lepsza, szczególnie w przypadku, gdy zależy nam na karaniu większych błędów bardziej, ale ignorowaniu małych różnic."
  echo "* MAPE (Mean Absolute Percentage Error): Średnia procentowa różnica między rzeczywistymi a przewidywanymi wartościami. Mniejsza wartość MAPE oznacza lepszy model, ponieważ mniejsze są odchylenia procentowe między przewidywanymi a rzeczywistymi wartościami."
  echo "* TT (Sec) (Train Time): Całkowity czas treningu modelu. Mniejszy czas TT oznacza szybszy model, co jest korzystne, szczególnie w przypadku dużych zbiorów danych lub konieczności szybkich predykcji."
  echo ""
  cat comparison_metrics.txt

  echo "### Rekomendacje modeli"
  echo "1. Logistic Regression (LR)"
  echo "* __Dokładność__: 90.09%"
  echo "* __AUC__: 0.7845"
  echo "* __F1__: 0.366"
  echo "* __Opis__: Logistic Regression to model liniowy stosowany w klasyfikacji binarnej. W przypadku tego zestawu danych wyróżnia się wysoką dokładnością, co sugeruje, że dobrze radzi sobie z klasyfikacją klientów."
  echo "* __Uzasadnienie__: Model ten jest dobrze zrozumiały, łatwy w interpretacji i pozwala na szybką identyfikację ważnych zmiennych. Dobrze nadaje się do zastosowań, gdzie ważna jest przejrzystość wyników."

  echo "2. Gradient Boosting Classifier (GBC)"
  echo "* __Dokładność__: 90.02%"
  echo "* __AUC__: 0.7945"
  echo "* __F1__: 0.3224"
  echo "* __Opis__: Gradient Boosting Classifier jest bardziej zaawansowanym modelem, który osiągnął najwyższy wynik AUC spośród rozważanych opcji. Algorytm ten iteracyjnie buduje kolejne modele, skupiając się na przykładach trudniejszych do klasyfikacji."
  echo "* __Uzasadnienie__: Model ten jest dobrym wyborem w sytuacjach, gdy głównym celem jest maksymalizacja dokładności klasyfikacji trudniejszych przypadków. Dzięki wysokiemu wynikowi AUC jest przydatny, gdy chcemy skupić się na dokładności przewidywań."

  echo "3. Light Gradient Boosting Machine (LightGBM)"
  echo "* __Dokładność__: 89.7%"
  echo "* __AUC__: 0.7899"
  echo "* __F1__: 0.3214"
  echo "* __Opis__: LightGBM to model zoptymalizowany pod kątem dużych zbiorów danych i wydajności obliczeniowej. Mimo że jego wyniki są minimalnie niższe niż w przypadku LR i GBC, jest w stanie skutecznie przetwarzać dane i dostosowywać się do bardziej złożonych zbiorów."
  echo "* __Uzasadnienie__: Model ten dobrze sprawdzi się w dalszych etapach, szczególnie jeśli dane będą bardziej złożone lub rozmiar zbioru danych wzrośnie. To mocna alternatywa dla bardziej wymagających obliczeniowo zadań."

  echo "### Wybór modelu"
  echo "Na podstawie wyników zalecane jest rozpoczęcie analizy od Logistic Regression ze względu na wysoką dokładność oraz łatwość interpretacji. Jeśli projekt będzie wymagał większej precyzji, rozważany będzie Gradient Boosting Classifier, który ma najlepszy wynik AUC i może zapewnić wyższą dokładność w bardziej złożonych klasyfikacjach."
  echo "### Dokładność i Średni błąd bezwzględny (MAE) dla wybranego modelu dla danych testowych"
  cat metrics.txt
  echo ""
  echo "Uzyskana dokładność modelu na poziomie 89,69% oraz MAE 0,103 wskazują na wysoką skuteczność klasyfikacji przy niskim średnim błędzie przewidywań, co sugeruje dobrze dopasowany model. W dalszym rozwijaniu modelu można rozważyć optymalizację hiperparametrów przy użyciu bardziej zaawansowanych technik tuningu lub eksperymentowanie z bardziej złożonymi modelami, jak gradient boosting, aby poprawić precyzję klasyfikacji przy zachowaniu interpretowalności wyników."

} > README.md